### ISSUE TITLE
error! npm run watch (async fs)

### ISSUE THREAD

**Issue by Kavehrafie** [RomainMazB/octobercms-tailwindcss-boilerplate#11]
kaveh@DESKTOP-8V6ENGO:/mnt/c/www/html/didaar/themes/zynx$ npm run watch

> tailwindcss-boilerplate@1.4.0 watch /mnt/c/www/html/didaar/themes/zynx
> webpack --watch --mode=development

/mnt/c/www/html/didaar/themes/zynx/modules/html-parser.js:28
            let pending = list.length;
                               ^

TypeError: Cannot read property 'length' of undefined
    at /mnt/c/www/html/didaar/themes/zynx/modules/html-parser.js:28:32
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tailwindcss-boilerplate@1.4.0 watch: `webpack --watch --mode=development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tailwindcss-boilerplate@1.4.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kaveh/.npm/_logs/2020-05-02T07_48_30_475Z-debug.log

**Comment by RomainMazB** [comment]
Hi @k1vehr1fie ,
Viewing the path of the error: `/mnt/c/www/html/didaar/themes/zynx/modules/html-parser.js`

It sounds like you renamed the boilerplate folder.

You shouldn't:
You need to leave the boilerplate directory as is, rename it to something generic like `tw-boilerplate`, or uninstall/re-install it and follow this steps:

Be sure the `.env` file is present at the root of your project, if not: run `php artisan october:env` command from `/mnt/c/www/html/didaar/` and check the `APP_URL` is correctly set to your local project's url: it should be something like `http://zynx.dev`.

Copy/paste the [`blank-src`](https://github.com/RomainMazB/octobercms-tailwindcss-boilerplate/blank-src/) folder inside your `themes` directory

If you want to rename the theme (like you did I guess for `zynx`): rename `blank-src` into `zynx-src` and modify the [`boilerplate.yaml`](https://github.com/RomainMazB/octobercms-tailwindcss-boilerplate/blob/master/boilerplate.yaml) file to:
```yaml
themeName: zynx
```
**(Optional but recommended)** Modify the [`zynx-src/new-theme.yaml`](https://github.com/RomainMazB/octobercms-tailwindcss-boilerplate/blob/master/blank-src/new-theme.yaml) file to something like:
```yaml
name: Zynx
description: Zynx awesome theme
author: k1vehr1fie
homepage: https://www.k1vehr1fie.com
code: 'zynx'
```

Then run `npm run watch` from `/mnt/c/www/html/didaar/themes/tw-boilerplate`: it will create the `zynx` final theme folder.

Activate the `zynx` theme from the backend front-end settings or `.env` file

All the installation steps are detailed in the [`README.md`](https://github.com/RomainMazB/octobercms-tailwindcss-boilerplate/#how-to-use) file.

`tw-boilerplate` directory will act as a "maestro": it will look inside your `zynx-src` folder, the only one you should modify in your creation process, and create/copy all the files inside of it to your `zynx` directory. You should never modify the `tw-boilerplate` folder.

Let me know if the problem is solved.

**Comment by RomainMazB** [comment]
No activity from a week, closing since it seems it was just a misuse.

Feel free to reopen if needed.
